export default {
  AT_LEAST_ONE_ITEM_REQUIRED: "AT_LEAST_ONE_ITEM_REQUIRED",

  FIELD_REQUIRED: "FIELD_REQUIRED",

  INVALID_BOOLEAN_FORMAT: "INVALID_BOOLEAN_FORMAT",
  INVALID_END_DATE: "INVALID_END_DATE",
  INVALID_FORMAT: "INVALID_FORMAT",
  INVALID_NUMBER: "INVALID_NUMBER",
  INVALID_START_DATE: "INVALID_START_DATE",
  INVALID_STRING: "INVALID_STRING",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PHONE: "INVALID_PHONE",
  INVALID_UUID_FORMAT: "INVALID_UUID_FORMAT",

  MAXIMUM_ROWS_LIMIT: {
    message: "MAXIMUM_ROWS_LIMIT",
    description: "Maximum number of rows exceeded. The maximum allowed is 100000.",
  },
  MISSING_REQUIRED_MAPPING_FIELDS: "MAPPING_MUST_INCLUDE_NAME_AND_ADDRESS_FIELDS",
  MUST_BE_POSITIVE: "MUST_BE_POSITIVE",
} as const;
